In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from pathlib import Path
df=pd.read_csv(Path("src/SchoolID_Prediction/raw_csv_dir/ExamData.csv"))

In [ ]:
df.head()

SchoolID  TrainingID       TDate  DurationID
0       366           1  28-09-2022           1
1       414           1  28-09-2022           1
2       567           1  28-09-2022           1
3      1471           1  28-09-2022           1
4      1902           1  28-09-2022           1

In [ ]:
df.dtypes

SchoolID       int64
TrainingID     int64
TDate         object
DurationID     int64
dtype: object

In [ ]:
df['TDate']=pd.to_datetime(df['TDate'],dayfirst=True)

In [ ]:
df.head(1)

SchoolID  TrainingID      TDate  DurationID
0       366           1 2022-09-28           1

In [ ]:
df.dtypes

SchoolID               int64
TrainingID             int64
TDate         datetime64[ns]
DurationID             int64
dtype: object

In [ ]:
df['day_name']=df.TDate.dt.day_name()

In [ ]:
df[(df['DurationID']==1) & (df['day_name']=='Sunday')]['TrainingID'].value_counts()

1    396
4    138
Name: TrainingID, dtype: int64

In [ ]:
df[(df['TrainingID']==1) & (df['DurationID']==1)]['day_name'].unique()

In [ ]:
df.head(10)

In [ ]:
df[(df['DurationID']==2) & (df['day_name']=='Sunday') & (df['month']==5)]

Empty DataFrame
Columns: [SchoolID, TrainingID, TDate, DurationID, day_name, month]
Index: []

In [ ]:
df['month']=df.TDate.dt.month

In [ ]:
df[(df['DurationID']==2) & (df['month']==5)]

In [ ]:
grp_by=df.groupby('TrainingID')

In [ ]:
for feature_unique,data in grp_by:
  print(feature_unique)
  print(data['day_name'].unique())
  print('==='*30)

In [ ]:
df[(df['DurationID']==4) & (df['day_name']=='Sunday') & (df['year']==2023)].TrainingID.unique()

array([1])

In [ ]:
df['year']=df.TDate.dt.year

In [ ]:
df_new=df[df.DurationID==1].iloc[:,0:4]

In [ ]:
df.head()

SchoolID  TrainingID      TDate  DurationID   day_name  month  year
0       366           1 2022-09-28           1  Wednesday      9  2022
1       414           1 2022-09-28           1  Wednesday      9  2022
2       567           1 2022-09-28           1  Wednesday      9  2022
3      1471           1 2022-09-28           1  Wednesday      9  2022
4      1902           1 2022-09-28           1  Wednesday      9  2022

In [ ]:
df_new['day'],df_new['month'],df_new['year']=df_new.TDate.dt.day,df_new.TDate.dt.month,df_new.TDate.dt.year

In [ ]:
df_new.head()

SchoolID  TrainingID      TDate  DurationID  day  month  year
0       366           1 2022-09-28           1   28      9  2022
1       414           1 2022-09-28           1   28      9  2022
2       567           1 2022-09-28           1   28      9  2022
3      1471           1 2022-09-28           1   28      9  2022
4      1902           1 2022-09-28           1   28      9  2022

In [ ]:
df_new[df_new['year']==2023]

SchoolID  TrainingID      TDate  DurationID  day  month  year
3198       1868           1 2023-01-01           1    1      1  2023
3199       1991           1 2023-01-01           1    1      1  2023
3200       2460           1 2023-01-01           1    1      1  2023
3201       2581           1 2023-01-01           1    1      1  2023
3202       3362           1 2023-01-01           1    1      1  2023
...         ...         ...        ...         ...  ...    ...   ...
54732      5519           6 2023-05-05           1    5      5  2023
54733      5972           6 2023-05-05           1    5      5  2023
54734      8250           6 2023-05-05           1    5      5  2023
54735      9225           6 2023-05-05           1    5      5  2023
54736      9760           6 2023-05-05           1    5      5  2023

[2291 rows x 7 columns]

In [ ]:
df_new[df_new['DurationID']==1].SchoolID.sort_values().index[0]

32736

In [ ]:
df_new[df_new.loc[df_new[df_new['DurationID']==1].SchoolID.sort_values().index,:]['year']==2023]['SchoolID']

In [ ]:
df_1=df_new[ (df_new['DurationID']==1) &  (df_new['TrainingID']==1)]

In [ ]:
df_1['month'].unique()

array([ 9, 10, 11, 12,  1,  2,  3,  4])

In [ ]:
df_new.month.unique()

array([ 9, 10, 11, 12,  1,  2,  3,  4,  5])

In [ ]:
df_1[df_1['month']]

In [ ]:
li=[]
for durationId in range(1,5):
  df_=df[(df['DurationID']==durationId)]
  for mon in df_.month.unique():
    print(f'{durationId=} and {mon=}')
    print(df_[df_['month']==mon].shape[0])
  print('===='*20)


array([1])

In [ ]:
df_new[df_new.loc[df_new[df_new['DurationID']==1].SchoolID.sort_values().index,:]['year']==2023]

<ipython-input-97-8d4c16a733da>:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_new[df_new.loc[df_new[df_new['DurationID']==1].SchoolID.sort_values().index,:]['year']==2023]


SchoolID  TrainingID      TDate  DurationID  day  month  year
3198       1868           1 2023-01-01           1    1      1  2023
3199       1991           1 2023-01-01           1    1      1  2023
3200       2460           1 2023-01-01           1    1      1  2023
3201       2581           1 2023-01-01           1    1      1  2023
3202       3362           1 2023-01-01           1    1      1  2023
...         ...         ...        ...         ...  ...    ...   ...
54732      5519           6 2023-05-05           1    5      5  2023
54733      5972           6 2023-05-05           1    5      5  2023
54734      8250           6 2023-05-05           1    5      5  2023
54735      9225           6 2023-05-05           1    5      5  2023
54736      9760           6 2023-05-05           1    5      5  2023

[2291 rows x 7 columns]

In [ ]:
df.loc[df.SchoolID.sort_values().index,:]

SchoolID  TrainingID      TDate  DurationID   day_name  month  year
3321          0           1 2023-01-01           6     Sunday      1  2023
38482         0           4 2023-03-01           4  Wednesday      3  2023
12126         0           4 2022-10-16           4     Sunday     10  2022
22907         0           6 2023-01-13           3     Friday      1  2023
11063         1           3 2023-01-03           5    Tuesday      1  2023
...         ...         ...        ...         ...        ...    ...   ...
7710       9999           3 2022-10-04           6    Tuesday     10  2022
44760      9999           1 2023-03-26           4     Sunday      3  2023
6939       9999           2 2022-12-26           6     Monday     12  2022
47482      9999           4 2023-04-05           6  Wednesday      4  2023
12347      9999           4 2022-10-16           6     Sunday     10  2022

[54974 rows x 7 columns]

In [ ]:
def second_to_minuts(second):
  if second<60:
    return f'00:00:{second}'
  if (second//60)>59:
    if second%3600<60:
      return f'{second//3600}:{second%3600}:00'
    hour=second//3600
    minuts=(second%3600)//60
    seconds=(second%3600)%60
    return f'{hour}:{second%3600}:{seconds}'
  return f'00:{second//60}:{second%60}'

In [ ]:
second_to_minuts(4000)
second=4000%3600
second

400

In [ ]:
seconds_=[second_to_minuts(second)  for second in range(1,len(df_new)+1)]

In [ ]:
seconds_[::-1][:10]

['1:389:00',
 '1:388:00',
 '1:387:00',
 '1:386:00',
 '1:385:00',
 '1:384:00',
 '1:383:00',
 '1:382:00',
 '1:381:00',
 '1:380:00']

In [ ]:
df_new['seconds']=[second  for second in range(1,len(df_new)+1)]

In [ ]:
df_new.head()

SchoolID  TrainingID      TDate  DurationID  day  month  year  seconds
0       366           1 2022-09-28           1   28      9  2022  00:00:1
1       414           1 2022-09-28           1   28      9  2022  00:00:2
2       567           1 2022-09-28           1   28      9  2022  00:00:3
3      1471           1 2022-09-28           1   28      9  2022  00:00:4
4      1902           1 2022-09-28           1   28      9  2022  00:00:5

In [ ]:
df_new[["day","month","year","seconds"]].apply(lambda a: f'{a[0]}:{a[1]}:{a[2]}:{a[3]}')

day                            28:28:28:28
month                              9:9:9:9
year                   2022:2022:2022:2022
seconds    00:00:1:00:00:2:00:00:3:00:00:4
dtype: object

In [ ]:
df_new['combine']=[ f'{value[0]}:{value[1]}:{value[2]}:{value[3]}' for value in df_new[["day","month","year","seconds"]].values]

In [ ]:
# pd.to_datetime(df_new['combine'],dayfirst=True,format='%d:%m:%Y:%H:%M:%S')

In [ ]:
df_new.head()

SchoolID  TrainingID      TDate  DurationID  day  month  year  seconds  \
0       366           1 2022-09-28           1   28      9  2022        1   
1       414           1 2022-09-28           1   28      9  2022        2   
2       567           1 2022-09-28           1   28      9  2022        3   
3      1471           1 2022-09-28           1   28      9  2022        4   
4      1902           1 2022-09-28           1   28      9  2022        5   

             combine  
0  28:9:2022:00:00:1  
1  28:9:2022:00:00:2  
2  28:9:2022:00:00:3  
3  28:9:2022:00:00:4  
4  28:9:2022:00:00:5

In [ ]:
x=df_new.drop(columns='SchoolID')
y=df_new['SchoolID']

### final


In [ ]:
df=pd.read_csv('ExamData.csv',date_parser=True)

In [ ]:
df['TDate']=pd.to_datetime(df.TDate,dayfirst=True)

In [ ]:
df.head()

SchoolID  TrainingID      TDate  DurationID
0       366           1 2022-09-28           1
1       414           1 2022-09-28           1
2       567           1 2022-09-28           1
3      1471           1 2022-09-28           1
4      1902           1 2022-09-28           1

In [ ]:
df_duration_1=df[df['DurationID']==1]

In [ ]:
df_duration_1.head(1)

SchoolID  TrainingID      TDate  DurationID
0       366           1 2022-09-28           1

In [ ]:
df_duration_1['month']=df_duration_1.TDate.dt.month

In [ ]:
test_df=pd.DataFrame()
for group,data in df_duration_1.groupby("month"):
  data=data
  data['hour']=list(range(1,len(data)+1))
  test_df=pd.concat((test_df,data))

In [ ]:
pd.set_option('display.max_rows', None)
test_df

In [ ]:
test_df.shape

(3989, 6)

In [ ]:
test_df['year']=test_df.TDate.dt.year
test_df['day']=test_df.TDate.dt.day

In [ ]:
test_df.head(1)

SchoolID  TrainingID      TDate  DurationID  month  hour  year  day
3198      1868           1 2023-01-01           1      1     1  2023    1

In [ ]:
from sklearn.model_selection import train_test_split
test_df=pd.DataFrame()
for group,data in df_duration_1.groupby("month"):
  data=data
  data['hour']=list(range(1,len(data)+1))
  test_df=pd.concat((test_df,data))
test_df['year']=test_df.TDate.dt.year
test_df['day']=test_df.TDate.dt.day
x=test_df.drop(columns=["TDate","DurationID",'SchoolID'])
y=test_df['SchoolID']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=10)

In [ ]:
x_train.shape

(3590, 5)

In [ ]:
import tensorflow as tf


In [ ]:
LAYERS=[
    tf.keras.layers.Input(shape=(x_train.shape[1],)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dense(256,activation='relu'),
    tf.keras.layers.Dense(64,activation='relu'),
    tf.keras.layers.Dense(32,activation='relu'),
    tf.keras.layers.Dense(16,activation='relu'),
    tf.keras.layers.Dense(1)
]

model=tf.keras.Sequential(LAYERS)

In [ ]:
model.compile(loss='mean_absolute_error',metrics=['mean_absolute_error'],optimizer='adam')

In [ ]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=1000)

In [ ]:
model.evaluate(x_test,y_test)

13/13 [==============================] - 0s 2ms/step - loss: 2371.4651 - mean_absolute_error: 2371.4651


[2371.465087890625, 2371.465087890625]

In [ ]:
x_train.head(1)

TrainingID  month  hour  year  day
43613           4      3   391  2023   22

In [ ]:
model.predict([[1,5,1,2023,7]])

1/1 [==============================] - 0s 61ms/step


array([[455.7065]], dtype=float32)

In [ ]:
y_train[0]

366

In [ ]:
x_train.iloc[0]

TrainingID       4
month            3
hour           391
year          2023
day             22
Name: 43613, dtype: int64

In [ ]:
model.predict([[4	,3	,391	,2023	,22]])

## Using Machine Learning


In [1]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.model_selection import GridSearchCV

In [2]:
raw_df=pd.read_csv('ExamData.csv')

In [3]:
raw_df.columns

Index(['SchoolID', 'TrainingID', 'TDate', 'DurationID'], dtype='object')

In [4]:
raw_df['TDate']=pd.to_datetime(raw_df.TDate,dayfirst=True)
raw_df['month']=raw_df.TDate.dt.month

In [5]:
from sklearn.model_selection import train_test_split
test_df=pd.DataFrame()
dataset_dict=dict()
for duration_id in raw_df.DurationID.unique():
  df_duration=raw_df[raw_df['DurationID']==duration_id]
  for group,data in df_duration.groupby("month"):
    data=data
    data['hour']=list(range(1,len(data)+1))
    test_df=pd.concat((test_df,data))
  dataset_dict.update({f'DurationID_{duration_id}':test_df})

In [ ]:
random_forest_params={"n_estimators":range(100,251,50),
                      "criterion":["squared_error", "absolute_error", "friedman_mse", "poisson"],
                      "min_samples_split":[2,3,5,6,8,9],
                      "ccp_alpha":[0.1,0.001,0.0001,1.0]
         }
random=RandomForestRegressor()
grid_random=GridSearchCV(estimator=random,param_grid=random_forest_params)
grid_random.fit(x_train,y_train)

In [ ]:
!pip install lightgbm

In [37]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from lightgbm import LGBMRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.tree import DecisionTreeRegressor
from xgboost import XGBRFRegressor 
models=[RandomForestRegressor(),KNeighborsRegressor(),LGBMRegressor(),GradientBoostingRegressor(),DecisionTreeRegressor(),XGBRFRegressor()]
final_score_dict=dict()
all_models_dict=dict()
for key in list(dataset_dict.keys())[:4]:
  model_dict=dict()
  score_dict=dict()
  models=[RandomForestRegressor(),KNeighborsRegressor(),LGBMRegressor(),GradientBoostingRegressor(),DecisionTreeRegressor(),XGBRFRegressor()]
  for model in models:
    test_df=dataset_dict.get(key)
    test_df['year']=test_df.TDate.dt.year
    test_df['day']=test_df.TDate.dt.day
    x=test_df.drop(columns=["TDate","DurationID",'SchoolID'])
    y=test_df['SchoolID']
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.15,random_state=10)
    model_=model
    model_.fit(x_train,y_train)
    r2_score=model_.score(x_test,y_test)
    model_name=str(model_).split("(")[0]
    model_dict.update( {model_name : model_} )
    score_dict.update( {f'{model_name}': r2_score} )
    # print(f'model_name is ======> {model_name}')
    # print(f'{key} =======>         score is {r2_score}')
  print(score_dict)
  all_models_dict.update( { key : model_dict } )
  final_score_dict.update( { key : score_dict } )
  # print(f'==========  finish {key}  ============')

{'RandomForestRegressor': 0.947927238831702, 'KNeighborsRegressor': 0.7812868245833846, 'LGBMRegressor': 0.6030035362678139, 'GradientBoostingRegressor': 0.2815579616292153, 'DecisionTreeRegressor': 0.9158075768812861, 'XGBRFRegressor': 0.09328452995955572}
{'RandomForestRegressor': 0.8454420553770107, 'KNeighborsRegressor': 0.6439731615822231, 'LGBMRegressor': 0.37660928389526294, 'GradientBoostingRegressor': 0.1349958034058173, 'DecisionTreeRegressor': 0.7585080830823211, 'XGBRFRegressor': 0.05072295078475686}
{'RandomForestRegressor': 0.7782601250173891, 'KNeighborsRegressor': 0.6354137939127809, 'LGBMRegressor': 0.2959201760787674, 'GradientBoostingRegressor': 0.09242804434912888, 'DecisionTreeRegressor': 0.6759844245154245, 'XGBRFRegressor': 0.06340770326320055}
{'RandomForestRegressor': 0.8906404927387989, 'KNeighborsRegressor': 0.7482903067025679, 'LGBMRegressor': 0.34614076667032123, 'GradientBoostingRegressor': 0.06974351845770588, 'DecisionTreeRegressor': 0.8479445919781864, 

In [ ]:

"""XGBRFRegressor(base_score=None, booster=None, callbacks=None,
               colsample_bylevel=None, colsample_bytree=None,
               early_stopping_rounds=None, enable_categorical=False,
               eval_metric=None, feature_types=None, gamma=None, gpu_id=None,
               grow_policy=None, importance_type=None,)""".split('(')

['XGBRFRegressor',
 'base_score=None, booster=None, callbacks=None,\n               colsample_bylevel=None, colsample_bytree=None,\n               early_stopping_rounds=None, enable_categorical=False,\n               eval_metric=None, feature_types=None, gamma=None, gpu_id=None,\n               grow_policy=None, importance_type=None,)']

In [ ]:
final_score_dict.get('DurationID_1')

{'RandomForestRegressor': 0.9455797430919721,
 'KNeighborsRegressor': 0.7812868245833846,
 'LGBMRegressor': 0.6030035362678139,
 'GradientBoostingRegressor': 0.2815579616292154,
 'DecisionTreeRegressor': 0.9041828904783002,
 'XGBRFRegressor': 0.09328452995955572}

In [ ]:
final_score_dict.get('DurationID_2')

{'RandomForestRegressor': 0.8478156378397731,
 'KNeighborsRegressor': 0.6439731615822231,
 'LGBMRegressor': 0.37660928389526294,
 'GradientBoostingRegressor': 0.1349958034058173,
 'DecisionTreeRegressor': 0.7746891613281023,
 'XGBRFRegressor': 0.05072295078475686}

In [12]:
final_score_dict.get('DurationID_3')

{'RandomForestRegressor': 0.778808078723475,
 'KNeighborsRegressor': 0.6354137939127809,
 'LGBMRegressor': 0.2959201760787674,
 'GradientBoostingRegressor': 0.09242804434912888,
 'DecisionTreeRegressor': 0.6793726850589714,
 'XGBRFRegressor': 0.06340770326320055}

In [ ]:
final_score_dict.get('DurationID_4')

{'RandomForestRegressor': 0.8914518930063544,
 'KNeighborsRegressor': 0.7482903067025679,
 'LGBMRegressor': 0.34614076667032123,
 'GradientBoostingRegressor': 0.06974351845770588,
 'DecisionTreeRegressor': 0.8452229940051678,
 'XGBRFRegressor': 0.031118349297794445}

In [8]:
all_models_dict.keys()

dict_keys(['DurationID_1', 'DurationID_2', 'DurationID_3', 'DurationID_4'])

In [9]:
all_models_dict.get( 'DurationID_1' )

{'RandomForestRegressor': RandomForestRegressor(),
 'KNeighborsRegressor': KNeighborsRegressor(),
 'LGBMRegressor': LGBMRegressor(),
 'GradientBoostingRegressor': GradientBoostingRegressor(),
 'DecisionTreeRegressor': DecisionTreeRegressor(),
 'XGBRFRegressor': XGBRFRegressor(base_score=None, booster=None, callbacks=None,
                colsample_bylevel=None, colsample_bytree=None,
                early_stopping_rounds=None, enable_categorical=False,
                eval_metric=None, feature_types=None, gamma=None, gpu_id=None,
                grow_policy=None, importance_type=None,
                interaction_constraints=None, max_bin=None,
                max_cat_threshold=None, max_cat_to_onehot=None,
                max_delta_step=None, max_depth=None, max_leaves=None,
                min_child_weight=None, missing=nan, monotone_constraints=None,
                n_estimators=100, n_jobs=None, num_parallel_tree=None,
                objective='reg:squarederror', predictor=None, ra

In [43]:
top_model_dict=dict()
for key in final_score_dict.keys():
  print(f'======   {key}    ======')
  temp_dict={  j:i for i,j in final_score_dict.get(key).items()  }
  # print(temp_dict)
  li=[  temp_dict.get(score) for score in sorted(list(temp_dict.keys()),reverse=True)[:2]  ]
  top_model_dict.update( {key:li} )
  print(li)

======   DurationID_1    ======
['RandomForestRegressor', 'DecisionTreeRegressor']
======   DurationID_2    ======
['RandomForestRegressor', 'DecisionTreeRegressor']
======   DurationID_3    ======
['RandomForestRegressor', 'DecisionTreeRegressor']
======   DurationID_4    ======
['RandomForestRegressor', 'DecisionTreeRegressor']


In [66]:
for duration_id in final_score_dict.keys():
  print(f'======== {duration_id=} ==============')
  for model_name in top_model_dict.get(duration_id):
    score=final_score_dict.get(duration_id).get(model_name)
    print(f'model_name ========>  {model_name}    score ====>  {score}')
  print('========='*20)

======== duration_id='DurationID_1' ==============
model_name ========>  RandomForestRegressor    score ====>  0.947927238831702
model_name ========>  DecisionTreeRegressor    score ====>  0.9158075768812861
======== duration_id='DurationID_2' ==============
model_name ========>  RandomForestRegressor    score ====>  0.8454420553770107
model_name ========>  DecisionTreeRegressor    score ====>  0.7585080830823211
======== duration_id='DurationID_3' ==============
model_name ========>  RandomForestRegressor    score ====>  0.7782601250173891
model_name ========>  DecisionTreeRegressor    score ====>  0.6759844245154245
======== duration_id='DurationID_4' ==============
model_name ========>  RandomForestRegressor    score ====>  0.8906404927387989
model_name ========>  DecisionTreeRegressor    score ====>  0.8479445919781864


In [47]:
from sklearn.metrics import r2_score
for duration_id in top_model_dict.keys():
  print(f'{duration_id}')
  ans=np.zeros(len(x_test))
  for model_name in top_model_dict.get(duration_id):
    model=all_models_dict.get(duration_id).get(model_name)
    print(model_name)
    y_pre=np.array(model.predict(x_test))
    ans=ans+y_pre
  final_y_pre=ans/2
  print(r2_score(y_test,final_y_pre))
  print('======='*20)


DurationID_1
RandomForestRegressor
DecisionTreeRegressor
-1.3853310282010414
DurationID_2
RandomForestRegressor
DecisionTreeRegressor
-1.1876711731240963
DurationID_3
RandomForestRegressor
DecisionTreeRegressor
-0.913170856287151
DurationID_4
RandomForestRegressor
DecisionTreeRegressor
0.8824669265030001


In [46]:
ans=np.zeros(len(x_test))
for model_name in top_model_dict.get('DurationID_1'):
  model=all_models_dict.get("DurationID_1").get(model_name)
  print(model_name)
  y_pre=np.array(model.predict(x_test))
  ans=ans+y_pre
r2_score(y_test,ans/3)

RandomForestRegressor
DecisionTreeRegressor


-0.20042465480216864

In [71]:
all_models_dict.get("DurationID_1").get('RandomForestRegressor').predict(x_test)

array([ 693.95, 9585.72, 9573.47, ..., 8413.53, 9625.7 , 9608.38])

In [72]:
y_test

29932     316
14180    8625
45768    4198
50849    8556
5949     6272
         ... 
49130    6434
27661    4606
5223     5423
21955    4026
23969    4074
Name: SchoolID, Length: 4054, dtype: int64

In [67]:
ans=np.zeros(len(x_test))
for model_name in top_model_dict.get('DurationID_2'):
  model=all_models_dict.get("DurationID_2").get(model_name)
  print(model_name)
  y_pre=np.array(model.predict(x_test))
  ans=ans+y_pre
r2_score(y_test,ans/3)

RandomForestRegressor
DecisionTreeRegressor


-0.09524371718924995

In [69]:
y_test

29932     316
14180    8625
45768    4198
50849    8556
5949     6272
         ... 
49130    6434
27661    4606
5223     5423
21955    4026
23969    4074
Name: SchoolID, Length: 4054, dtype: int64

In [68]:
ans

array([  875.57, 19110.3 , 18580.37, ...,  8346.59, 19109.52, 19159.8 ])

In [49]:
raw_df_copy=raw_df.copy()

SchoolID       True
TrainingID     True
TDate         False
DurationID     True
month          True
dtype: bool

SchoolID       int64
TrainingID     int64
TDate         object
DurationID     int64
dtype: object

In [54]:
column_name_with_dtype={column:'int16' for column in raw_df_copy.columns if raw_df_copy[column].dtypes in ['int','float']}

In [55]:
column_name_with_dtype

{'SchoolID': 'int16',
 'TrainingID': 'int16',
 'DurationID': 'int16',
 'month': 'int16'}

In [58]:
raw_df_copy.dtypes

SchoolID               int64
TrainingID             int64
TDate         datetime64[ns]
DurationID             int64
month                  int64
dtype: object

In [57]:
raw_df_copy.astype(column_name_with_dtype).dtypes

SchoolID               int16
TrainingID             int16
TDate         datetime64[ns]
DurationID             int16
month                  int16
dtype: object

In [60]:
import os

In [61]:
os.path.getsize('/content/ExamData.csv')

1148613

In [63]:
with open('demo.json' ,'w') as f:
  pass

In [65]:
x_train.head()

TrainingID  month  hour  year  day
39319           7      3   316  2023    4
51619           7      4   403  2023   22
19894           6     10  1701  2022   21
12190           4     10  1067  2022   16
32829           3      2   535  2023    7

In [64]:
import json
from json.decoder import JSONDecodeError

with open('demo.json','r') as f:
  try:
    json.load(f)
  except JSONDecodeError as e:
    print('erro')

erro
